name: simple_state_manager
description: A package providing state management utilities for Flutter applications. It includes a `Manager` class for managing state changes and a `StateBuilder` widget for efficiently rebuilding parts of the UI based on state changes.
  The `Manager` class allows for the management and manipulation of application state through a `ValueNotifier`, providing methods to emit and update states. The `StateBuilder` widget is a customizable widget that efficiently updates its children based on changes in the managed state.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true